version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: mainframe:9000/sr-portal_backend:v1.1.27
    container_name: 'sr-portal_backend'
    ports:
      - '2000:5000'
    networks:
      - dev
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  dev:
    external: true
